package entity;

// Generated 2015-03-11 20:05:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "mareko")
public class Categories implements java.io.Serializable {

	private Integer idCategories;
	private String bookCategoryName;
	private Set<Books> bookses = new HashSet<Books>(0);

	public Categories() {
	}

	public Categories(String bookCategoryName, Set<Books> bookses) {
		this.bookCategoryName = bookCategoryName;
		this.bookses = bookses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_categories", unique = true, nullable = false)
	public Integer getIdCategories() {
		return this.idCategories;
	}

	public void setIdCategories(Integer idCategories) {
		this.idCategories = idCategories;
	}

	@Column(name = "book_category_name", length = 45)
	public String getBookCategoryName() {
		return this.bookCategoryName;
	}

	public void setBookCategoryName(String bookCategoryName) {
		this.bookCategoryName = bookCategoryName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "books_has_categories", catalog = "mareko", joinColumns = { @JoinColumn(name = "categories_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "book_id", nullable = false, updatable = false) })
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
